# Generated by Django 5.0.7 on 2025-02-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', max_length=255, upload_to='article_thumbs/'),
        ),
    ]
